### ISSUE TITLE
Feature: create a DAI-DOLA swap feature using Crv contract

### ISSUE THREAD

**Issue by webmass** [InverseFinance/inverse-web#39]
Crv does not support url based links for specific swaps =>

In addition to the current stabilizer, create a DAI-DOLA swap interface in Inverse that uses the crv contract

**Comment by nourharidy** [comment]
Would be interesting to have a unified swap interface for both INV and DOLA that finds and routes through the best route between 1inch (which already covers Sushi and Uniswap), Curve and the Stabilizer.

A more sophisticated feature (maybe to be added later) would be to combine different routes. Example: ETH->INV would route through ETH->USDC on 1inch, USDC->DOLA on Curve and Stabilizer, DOLA->INV on 1inch(sushi) all in 1 tx. Some issues to discuss: 1) this requires an additional contract to support multiple routes in 1 tx 2) gas costs might be a problem
