### ISSUE TITLE
Add repay all button

### ISSUE THREAD

**Issue by nourharidy** [InverseFinance/inverse-web#46]
Currently, when a user repays the maximum possible amount, additional interest is accrued while their transaction is pending, leaving a small amount of dust as debt.

Similar to https://old.inverse.finance/banking, we need an optional Repay All button to be added to the repay modal of all borrowable markets except ETH (Feature is not supported by the ETH market contract)

In order to instruct a market contract to repay all debt, we need to set the repay amount to Solidity's max uint256 value, which will be then changed by the contract to be the user's all outstanding debt within that market

For reference, please check https://github.com/InverseFinance/inverse-frontend/blob/4d95a41de0952989549a99b6d07b98f17943e82f/src/store/index.js#L809

**Comment by webmass** [comment]
Also added the withdraw all, using the same withdraw all logic from v1
